# Generated by Django 3.1.5 on 2021-02-05 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercebackend", "0010_auto_20210205_0723"),
        ("cryptopayment", "0002_invoice_total_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="transaction",
            new_name="btc_address_wif",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
        migrations.AddField(
            model_name="payment",
            name="cart",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="commercebackend.cartmodel",
            ),
            preserve_default=False,
        ),
    ]
