# Generated by Django 3.1.5 on 2021-01-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercebackend", "0003_auto_20210124_2309"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitemmodel",
            name="amount",
            field=models.IntegerField(default=1),
        ),
    ]
