# Generated by Django 3.1.5 on 2021-02-01 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("commercebackend", "0005_auto_20210128_1156"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitemmodel",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="cartitemmodel",
            old_name="modified_on",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="cartmodel",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="cartmodel",
            old_name="modified_on",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="ordermodel",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="ordermodel",
            old_name="modified_on",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="shippingmodel",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="shippingmodel",
            old_name="modified_on",
            new_name="modified_at",
        ),
        migrations.RemoveField(
            model_name="cartitemmodel",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="cartmodel",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="ordermodel",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="shippingmodel",
            name="deleted",
        ),
        migrations.AddField(
            model_name="cartitemmodel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartitemmodel",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cartitemmodel_deletedby",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cartmodel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartmodel",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cartmodel_deletedby",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordermodel_deletedby",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shippingmodel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shippingmodel",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shippingmodel_deletedby",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
