# Generated by Django 3.1.5 on 2021-02-01 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commercebackend', '0006_auto_20210201_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='ordered_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
