# Generated by Django 3.1.5 on 2021-02-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercebackend", "0009_auto_20210204_2216"),
    ]

    operations = [
        migrations.RemoveField(model_name="cartmodel", name="items"),
        migrations.AddField(
            model_name="cartmodel",
            name="items",
            field=models.ManyToManyField(to="commercebackend.CartItemModel"),
        ),
    ]
