# Generated by Django 3.1.5 on 2021-02-05 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercebackend', '0010_auto_20210205_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmodel',
            name='is_current',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='shippingmodel',
            unique_together={('user', 'is_current')},
        ),
    ]
