# Generated by Django 3.1.5 on 2021-01-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryfrontend', '0002_auto_20210119_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='death_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='published_date',
            field=models.DateField(null=True),
        ),
    ]
