# Generated by Django 3.1.5 on 2021-01-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryfrontend', '0005_auto_20210119_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='libraryfrontend.authormodel'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='libraryfrontend.categorymodel'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='libraryfrontend.publishermodel'),
        ),
    ]
