# Generated by Django 3.1.5 on 2021-01-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryfrontend", "0008_auto_20210123_1244"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authormodel",
            name="author_image",
            field=models.ImageField(default="placeholder_author.png", upload_to=""),
        ),
        migrations.AlterField(
            model_name="bookmodel",
            name="book_cover",
            field=models.ImageField(default="placeholder_cover.png", upload_to=""),
        ),
    ]
