# Generated by Django 3.1.5 on 2021-01-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryfrontend", "0009_auto_20210123_1437"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publishermodel",
            name="descripton",
            field=models.TextField(blank=True, null=True),
        ),
    ]
